CREATE PROC [hana].[SP_DELIVERY_ITEM_MERGE] AS
MERGE hana.DELIVERY_ITEM T
USING hana.DELIVERY_ITEM_DELTA S ON T.DELIVERY_ITEM_CODE=S.DELIVERY_ITEM_CODE and T.DELIVERY_CODE=S.DELIVERY_CODE
WHEN MATCHED THEN
UPDATE SET 
UNLOADING_POINT_CODE=S.UNLOADING_POINT_CODE
,DELIVERY_HEADER_CHANGE_DATE=S.DELIVERY_HEADER_CHANGE_DATE
,TOTAL_NO_DELIVERY_PACKAGES=S.TOTAL_NO_DELIVERY_PACKAGES
,DOC_DATE=S.DOC_DATE
,BILL_OF_LADING_NO=S.BILL_OF_LADING_NO
,DELIVERY_VERSION_NO=S.DELIVERY_VERSION_NO
,DELIVERY_HEADER_RECORD_CREATE_DATE=S.DELIVERY_HEADER_RECORD_CREATE_DATE
,DELIVERY_HEADER_RECORD_CREATE_BY=S.DELIVERY_HEADER_RECORD_CREATE_BY
,CUSTOMER_GROUP_CODE=S.CUSTOMER_GROUP_CODE
,DELIVERY_PICKING_DATE=S.DELIVERY_PICKING_DATE
,SOLD_TO_CODE=S.SOLD_TO_CODE
,SHIP_TO_CODE=S.SHIP_TO_CODE
,LOADING_DATE=S.LOADING_DATE
,DELIVERY_TYPE_CODE=S.DELIVERY_TYPE_CODE
,DELIVERY_DATE=S.DELIVERY_DATE
,WAREHOUSE_NO=S.WAREHOUSE_NO
,DELIVERY_PRIORITY_CODE=S.DELIVERY_PRIORITY_CODE
,TIME_PRICING_GOODS_ISSUE_TIME=S.TIME_PRICING_GOODS_ISSUE_TIME
,INVOICE_DATE_CALENDAR_CODE=S.INVOICE_DATE_CALENDAR_CODE
,PROOF_OF_DELIVERY_DATE=S.PROOF_OF_DELIVERY_DATE
,RELEVANT_FOR_POD_PROCESS_IND=S.RELEVANT_FOR_POD_PROCESS_IND
,TRANSPORTATION_GROUP_CODE=S.TRANSPORTATION_GROUP_CODE
,SD_DOC_CATEGORY_CODE=S.SD_DOC_CATEGORY_CODE
,VOLUME_UOM=S.VOLUME_UOM
,SHIPPING_CONDITION_CODE=S.SHIPPING_CONDITION_CODE
,SHIPPING_RECEIVING_POINT=S.SHIPPING_RECEIVING_POINT
,INTERCOMPANY_BILLING_DIST_CH_CODE=S.INTERCOMPANY_BILLING_DIST_CH_CODE
,PLANNED_GOODS_MOVEMENT_DATE=S.PLANNED_GOODS_MOVEMENT_DATE
,ACTUAL_GOODS_MOVEMENT_DATE=S.ACTUAL_GOODS_MOVEMENT_DATE
,SD_DOC_CURRENCY_CODE=S.SD_DOC_CURRENCY_CODE
,EHAULIER_DELIVERY_CONFIRMATION_DATE=S.EHAULIER_DELIVERY_CONFIRMATION_DATE
,EHAULIER_USER_FIRST_NAME=S.EHAULIER_USER_FIRST_NAME
,EHAULIER_USER_LAST_NAME=S.EHAULIER_USER_LAST_NAME
,DELIVERY_COMBINATION_CRITERIA=S.DELIVERY_COMBINATION_CRITERIA
,DELIVERY_ITEM_LAST_CHANGE_DATE=S.DELIVERY_ITEM_LAST_CHANGE_DATE
,DELIVERY_ITEM_RECORD_CREATE_DATE=S.DELIVERY_ITEM_RECORD_CREATE_DATE
,DELIVERY_ITEM_RECORD_CREATE_BY=S.DELIVERY_ITEM_RECORD_CREATE_BY
,RELEVANT_FOR_BILLING_IND=S.RELEVANT_FOR_BILLING_IND
,POD_IND=S.POD_IND
,MATERIAL_GROUP_CODE=S.MATERIAL_GROUP_CODE
,MATERIAL_NO=S.MATERIAL_NO
,MATERIAL_ENTERED_CODE=S.MATERIAL_ENTERED_CODE
,DELIVERY_ITEM_BUOM=S.DELIVERY_ITEM_BUOM
,MATERIAL_TYPE_CODE=S.MATERIAL_TYPE_CODE
,POD_CONTROL_IND=S.POD_CONTROL_IND
,PRODUCT_HIERARCHY_SKU_CODE=S.PRODUCT_HIERARCHY_SKU_CODE
,DELIVERY_ITEM_CATEGORY_CODE=S.DELIVERY_ITEM_CATEGORY_CODE
,SALES_OFFICE_CODE=S.SALES_OFFICE_CODE
,SALES_GROUP_CODE=S.SALES_GROUP_CODE
,SENDING_RECEIVING_PLANT_CODE=S.SENDING_RECEIVING_PLANT_CODE
,ITEMS_OVERALL_REJECTION_STATUS_CODE=S.ITEMS_OVERALL_REJECTION_STATUS_CODE
,CONFIRMATION_STATUS_CODE=S.CONFIRMATION_STATUS_CODE
,ITEM_OVERALL_DELIVERY_STATUS_CODE=S.ITEM_OVERALL_DELIVERY_STATUS_CODE
,ITEM_DELIVERY_STATUS_CODE=S.ITEM_DELIVERY_STATUS_CODE
,ITEM_GOODS_MOVEMENT_STATUS_CODE=S.ITEM_GOODS_MOVEMENT_STATUS_CODE
,SALES_ORG_CODE=S.SALES_ORG_CODE
,DELIVERY_NET_PRICE=S.DELIVERY_NET_PRICE
,DELIVERY_NET_VALUE_IN_DC=S.DELIVERY_NET_VALUE_IN_DC
,NET_WEIGHT=S.NET_WEIGHT
,DELIVERY_VOLUME=S.DELIVERY_VOLUME
,GROSS_WEIGHT=S.GROSS_WEIGHT
,Del_Reusable_Last_Dtm = S.Del_Reusable_Last_Dtm
,INCOTERM_CODE	 = S.INCOTERM_CODE
,DESTINATION_COUNTRY_CODE	 = S.DESTINATION_COUNTRY_CODE
,ORIGIN_COUNTRY_CODE	 = S.ORIGIN_COUNTRY_CODE
,DOC_REFERENCE	 = S.DOC_REFERENCE
,SO_REF_DOC_NO	 = S.SO_REF_DOC_NO
,REF_DOC_NO_AND_ITEM_NO	 = S.REF_DOC_NO_AND_ITEM_NO
,SO_REF_DOC_ITEM_NO	 = S.SO_REF_DOC_ITEM_NO
,STORAGE_LOCATION_CODE	 = S.STORAGE_LOCATION_CODE
,SALES_DOC_BILLING_STATUS_CODE	 = S.SALES_DOC_BILLING_STATUS_CODE
,DELIVERY_STATUS_CODE	 = S.DELIVERY_STATUS_CODE
,OVERALL_DELIVERY_BLOCK_STATUS_CODE	 = S.OVERALL_DELIVERY_BLOCK_STATUS_CODE
,OVERALL_BILLING_BLOCK_STATUS_CODE	 = S.OVERALL_BILLING_BLOCK_STATUS_CODE
,SALES_DOC_HEADER_POD_STATUS_CODE	 = S.SALES_DOC_HEADER_POD_STATUS_CODE
,ITEM_BILLING_BLOCK_STATUS_CODE	 = S.ITEM_BILLING_BLOCK_STATUS_CODE
,ITEM_DELIVERY_BLOCK_STATUS_CODE	 = S.ITEM_DELIVERY_BLOCK_STATUS_CODE
,ITEM_POD_STATUS_CODE	 = S.ITEM_POD_STATUS_CODE
,SOLD_TO_PARTY_NAME	 = S.SOLD_TO_PARTY_NAME
,SHIP_TO_PARTY_NAME	 = S.SHIP_TO_PARTY_NAME
,CHANGE_BY	 = S.CHANGE_BY
,PICKED_ITEM_LOCATION	 = S.PICKED_ITEM_LOCATION
,BILLING_BLOCK_CODE	 = S.BILLING_BLOCK_CODE
,CUSTOMER_CREDIT_GROUP_CODE	 = S.CUSTOMER_CREDIT_GROUP_CODE
,INCOTERM_DESTINATION_NAME	 = S.INCOTERM_DESTINATION_NAME
,SHIPPING_PRICING_PROCEDURE_CODE	 = S.SHIPPING_PRICING_PROCEDURE_CODE
,CREDIT_CONTROL_AREA_CODE	 = S.CREDIT_CONTROL_AREA_CODE
,DELIVERY_BLOCK_CODE	 = S.DELIVERY_BLOCK_CODE
,Bill_to_party	 = S.Bill_to_party
,Bill_to_party_name	 = S.Bill_to_party_name
,Payer	 = S.Payer
,Payer_Name	 = S.Payer_Name
,vessel_partner	 = S.vessel_partner
,vessel_partner_name	 = S.vessel_partner_name
,DELIVERY_ITEM_ORIGINAL_QTY	 = S.DELIVERY_ITEM_ORIGINAL_QTY
,CUSTOMER_GROUP1_CODE	 = S.CUSTOMER_GROUP1_CODE
,CUSTOMER_GROUP2_CODE	 = S.CUSTOMER_GROUP2_CODE
,CUSTOMER_GROUP3_CODE	 = S.CUSTOMER_GROUP3_CODE
,MATERIAL_GROUP1_CODE	 = S.MATERIAL_GROUP1_CODE
,MATERIAL_GROUP2_CODE	 = S.MATERIAL_GROUP2_CODE
,MATERIAL_GROUP3_CODE	 = S.MATERIAL_GROUP3_CODE
,ITEM_TYPE_CODE	 = S.ITEM_TYPE_CODE
,ORIGINATING_DOC_NO	 = S.ORIGINATING_DOC_NO
,DISTRIBUTION_CHANNEL_CODE	 = S.DISTRIBUTION_CHANNEL_CODE
,DIVISION_CODE	 = S.DIVISION_CODE
,BILLING_BLOCK_REASON_DESC	 = S.BILLING_BLOCK_REASON_DESC
,Sales_Organisation_Name	 = S.Sales_Organisation_Name
,DELIVERY_BLOCK_REASON_SCOPE_DESC	 = S.DELIVERY_BLOCK_REASON_SCOPE_DESC
,SHIPPING_CONDITION_DESC	 = S.SHIPPING_CONDITION_DESC
,CREDIT_CONTROL_AREA_DESC	 = S.CREDIT_CONTROL_AREA_DESC
,DIVISION_NAME	 = S.DIVISION_NAME
,DISTRIBUTION_CHANNEL_NAME	 = S.DISTRIBUTION_CHANNEL_NAME
,material_pricing_group1	 = S.material_pricing_group1
,material_pricing_group2	 = S.material_pricing_group2
,material_pricing_group3	 = S.material_pricing_group3
,Material_Desc_1	 = S.Material_Desc_1
,Plant_Name	 = S.Plant_Name
,MATERIAL_GROUP_DESC	 = S.MATERIAL_GROUP_DESC
,SALES_GROUP_DESC	 = S.SALES_GROUP_DESC
,SALES_OFFICE_DESC	 = S.SALES_OFFICE_DESC
WHEN NOT MATCHED BY TARGET
THEN
INSERT (UNLOADING_POINT_CODE					
,DELIVERY_HEADER_CHANGE_DATE			
,TOTAL_NO_DELIVERY_PACKAGES			
,DOC_DATE						
,BILL_OF_LADING_NO						
,DELIVERY_VERSION_NO					
,DELIVERY_HEADER_RECORD_CREATE_DATE	
,DELIVERY_HEADER_RECORD_CREATE_BY		
,CUSTOMER_GROUP_CODE					
,DELIVERY_PICKING_DATE					
,SOLD_TO_CODE							
,SHIP_TO_CODE							
,LOADING_DATE							
,DELIVERY_TYPE_CODE					
,DELIVERY_DATE							
,WAREHOUSE_NO							
,DELIVERY_PRIORITY_CODE				
,TIME_PRICING_GOODS_ISSUE_TIME			
,INVOICE_DATE_CALENDAR_CODE			
,PROOF_OF_DELIVERY_DATE				
,RELEVANT_FOR_POD_PROCESS_IND			
,TRANSPORTATION_GROUP_CODE				
,DELIVERY_CODE							
,SD_DOC_CATEGORY_CODE					
,VOLUME_UOM							
,SHIPPING_CONDITION_CODE				
,SHIPPING_RECEIVING_POINT				
,INTERCOMPANY_BILLING_DIST_CH_CODE		
,PLANNED_GOODS_MOVEMENT_DATE			
,ACTUAL_GOODS_MOVEMENT_DATE			
,SD_DOC_CURRENCY_CODE					
,EHAULIER_DELIVERY_CONFIRMATION_DATE	
,EHAULIER_USER_FIRST_NAME				
,EHAULIER_USER_LAST_NAME				
,DELIVERY_COMBINATION_CRITERIA			
,DELIVERY_ITEM_LAST_CHANGE_DATE		
,DELIVERY_ITEM_RECORD_CREATE_DATE		
,DELIVERY_ITEM_RECORD_CREATE_BY		
,RELEVANT_FOR_BILLING_IND				
,POD_IND								
,MATERIAL_GROUP_CODE					
,MATERIAL_NO							
,MATERIAL_ENTERED_CODE					
,DELIVERY_ITEM_BUOM					
,MATERIAL_TYPE_CODE					
,POD_CONTROL_IND						
,DELIVERY_ITEM_CODE					
,PRODUCT_HIERARCHY_SKU_CODE			
,DELIVERY_ITEM_CATEGORY_CODE			
,SALES_OFFICE_CODE						
,SALES_GROUP_CODE						
,SENDING_RECEIVING_PLANT_CODE			
,ITEMS_OVERALL_REJECTION_STATUS_CODE	
,CONFIRMATION_STATUS_CODE				
,ITEM_OVERALL_DELIVERY_STATUS_CODE		
,ITEM_DELIVERY_STATUS_CODE				
,ITEM_GOODS_MOVEMENT_STATUS_CODE		
,SALES_ORG_CODE						
,DELIVERY_NET_PRICE					
,DELIVERY_NET_VALUE_IN_DC				
,NET_WEIGHT							
,DELIVERY_VOLUME						
,GROSS_WEIGHT							
,Del_Reusable_Last_Dtm
,INCOTERM_CODE
,DESTINATION_COUNTRY_CODE
,ORIGIN_COUNTRY_CODE
,DOC_REFERENCE
,SO_REF_DOC_NO
,REF_DOC_NO_AND_ITEM_NO
,SO_REF_DOC_ITEM_NO
,STORAGE_LOCATION_CODE
,SALES_DOC_BILLING_STATUS_CODE
,DELIVERY_STATUS_CODE
,OVERALL_DELIVERY_BLOCK_STATUS_CODE
,OVERALL_BILLING_BLOCK_STATUS_CODE
,SALES_DOC_HEADER_POD_STATUS_CODE
,ITEM_BILLING_BLOCK_STATUS_CODE
,ITEM_DELIVERY_BLOCK_STATUS_CODE
,ITEM_POD_STATUS_CODE
,SOLD_TO_PARTY_NAME
,SHIP_TO_PARTY_NAME
,CHANGE_BY
,PICKED_ITEM_LOCATION
,BILLING_BLOCK_CODE
,CUSTOMER_CREDIT_GROUP_CODE
,INCOTERM_DESTINATION_NAME
,SHIPPING_PRICING_PROCEDURE_CODE
,CREDIT_CONTROL_AREA_CODE
,DELIVERY_BLOCK_CODE
,Bill_to_party
,Bill_to_party_name
,Payer
,Payer_Name
,vessel_partner
,vessel_partner_name
,DELIVERY_ITEM_ORIGINAL_QTY
,CUSTOMER_GROUP1_CODE
,CUSTOMER_GROUP2_CODE
,CUSTOMER_GROUP3_CODE
,MATERIAL_GROUP1_CODE
,MATERIAL_GROUP2_CODE
,MATERIAL_GROUP3_CODE
,ITEM_TYPE_CODE
,ORIGINATING_DOC_NO
,DISTRIBUTION_CHANNEL_CODE
,DIVISION_CODE
,BILLING_BLOCK_REASON_DESC
,Sales_Organisation_Name
,DELIVERY_BLOCK_REASON_SCOPE_DESC
,SHIPPING_CONDITION_DESC
,CREDIT_CONTROL_AREA_DESC
,DIVISION_NAME
,DISTRIBUTION_CHANNEL_NAME
,material_pricing_group1
,material_pricing_group2
,material_pricing_group3
,Material_Desc_1
,Plant_Name
,MATERIAL_GROUP_DESC
,SALES_GROUP_DESC
,SALES_OFFICE_DESC
)
VALUES ( S.UNLOADING_POINT_CODE					
,S.DELIVERY_HEADER_CHANGE_DATE			
,S.TOTAL_NO_DELIVERY_PACKAGES			
,S.DOC_DATE						
,S.BILL_OF_LADING_NO						
,S.DELIVERY_VERSION_NO					
,S.DELIVERY_HEADER_RECORD_CREATE_DATE	
,S.DELIVERY_HEADER_RECORD_CREATE_BY		
,S.CUSTOMER_GROUP_CODE					
,S.DELIVERY_PICKING_DATE					
,S.SOLD_TO_CODE							
,S.SHIP_TO_CODE							
,S.LOADING_DATE							
,S.DELIVERY_TYPE_CODE					
,S.DELIVERY_DATE							
,S.WAREHOUSE_NO							
,S.DELIVERY_PRIORITY_CODE				
,S.TIME_PRICING_GOODS_ISSUE_TIME			
,S.INVOICE_DATE_CALENDAR_CODE			
,S.PROOF_OF_DELIVERY_DATE				
,S.RELEVANT_FOR_POD_PROCESS_IND			
,S.TRANSPORTATION_GROUP_CODE				
,S.DELIVERY_CODE							
,S.SD_DOC_CATEGORY_CODE					
,S.VOLUME_UOM							
,S.SHIPPING_CONDITION_CODE				
,S.SHIPPING_RECEIVING_POINT				
,S.INTERCOMPANY_BILLING_DIST_CH_CODE		
,S.PLANNED_GOODS_MOVEMENT_DATE			
,S.ACTUAL_GOODS_MOVEMENT_DATE			
,S.SD_DOC_CURRENCY_CODE					
,S.EHAULIER_DELIVERY_CONFIRMATION_DATE	
,S.EHAULIER_USER_FIRST_NAME				
,S.EHAULIER_USER_LAST_NAME				
,S.DELIVERY_COMBINATION_CRITERIA			
,S.DELIVERY_ITEM_LAST_CHANGE_DATE		
,S.DELIVERY_ITEM_RECORD_CREATE_DATE		
,S.DELIVERY_ITEM_RECORD_CREATE_BY		
,S.RELEVANT_FOR_BILLING_IND				
,S.POD_IND								
,S.MATERIAL_GROUP_CODE					
,S.MATERIAL_NO							
,S.MATERIAL_ENTERED_CODE					
,S.DELIVERY_ITEM_BUOM					
,S.MATERIAL_TYPE_CODE					
,S.POD_CONTROL_IND						
,S.DELIVERY_ITEM_CODE					
,S.PRODUCT_HIERARCHY_SKU_CODE			
,S.DELIVERY_ITEM_CATEGORY_CODE			
,S.SALES_OFFICE_CODE						
,S.SALES_GROUP_CODE						
,S.SENDING_RECEIVING_PLANT_CODE			
,S.ITEMS_OVERALL_REJECTION_STATUS_CODE	
,S.CONFIRMATION_STATUS_CODE				
,S.ITEM_OVERALL_DELIVERY_STATUS_CODE		
,S.ITEM_DELIVERY_STATUS_CODE				
,S.ITEM_GOODS_MOVEMENT_STATUS_CODE		
,S.SALES_ORG_CODE						
,S.DELIVERY_NET_PRICE					
,S.DELIVERY_NET_VALUE_IN_DC				
,S.NET_WEIGHT							
,S.DELIVERY_VOLUME						
,S.GROSS_WEIGHT							
,S.Del_Reusable_Last_Dtm
,S.INCOTERM_CODE
,S.DESTINATION_COUNTRY_CODE
,S.ORIGIN_COUNTRY_CODE
,S.DOC_REFERENCE
,S.SO_REF_DOC_NO
,S.REF_DOC_NO_AND_ITEM_NO
,S.SO_REF_DOC_ITEM_NO
,S.STORAGE_LOCATION_CODE
,S.SALES_DOC_BILLING_STATUS_CODE
,S.DELIVERY_STATUS_CODE
,S.OVERALL_DELIVERY_BLOCK_STATUS_CODE
,S.OVERALL_BILLING_BLOCK_STATUS_CODE
,S.SALES_DOC_HEADER_POD_STATUS_CODE
,S.ITEM_BILLING_BLOCK_STATUS_CODE
,S.ITEM_DELIVERY_BLOCK_STATUS_CODE
,S.ITEM_POD_STATUS_CODE
,S.SOLD_TO_PARTY_NAME
,S.SHIP_TO_PARTY_NAME
,S.CHANGE_BY
,S.PICKED_ITEM_LOCATION
,S.BILLING_BLOCK_CODE
,S.CUSTOMER_CREDIT_GROUP_CODE
,S.INCOTERM_DESTINATION_NAME
,S.SHIPPING_PRICING_PROCEDURE_CODE
,S.CREDIT_CONTROL_AREA_CODE
,S.DELIVERY_BLOCK_CODE
,S.Bill_to_party
,S.Bill_to_party_name
,S.Payer
,S.Payer_Name
,S.vessel_partner
,S.vessel_partner_name
,S.DELIVERY_ITEM_ORIGINAL_QTY
,S.CUSTOMER_GROUP1_CODE
,S.CUSTOMER_GROUP2_CODE
,S.CUSTOMER_GROUP3_CODE
,S.MATERIAL_GROUP1_CODE
,S.MATERIAL_GROUP2_CODE
,S.MATERIAL_GROUP3_CODE
,S.ITEM_TYPE_CODE
,S.ORIGINATING_DOC_NO
,S.DISTRIBUTION_CHANNEL_CODE
,S.DIVISION_CODE
,S.BILLING_BLOCK_REASON_DESC
,S.Sales_Organisation_Name
,S.DELIVERY_BLOCK_REASON_SCOPE_DESC
,S.SHIPPING_CONDITION_DESC
,S.CREDIT_CONTROL_AREA_DESC
,S.DIVISION_NAME
,S.DISTRIBUTION_CHANNEL_NAME
,S.material_pricing_group1
,S.material_pricing_group2
,S.material_pricing_group3
,S.Material_Desc_1
,S.Plant_Name
,S.MATERIAL_GROUP_DESC
,S.SALES_GROUP_DESC
,S.SALES_OFFICE_DESC
);
